import com.github.benmanes.gradle.versions.VersionsPlugin

plugins {
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.kapt) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.apollo) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.binary.compatibility.validator) apply false
    alias(libs.plugins.wire) apply false
    alias(libs.plugins.nexus.staging) apply false
    alias(libs.plugins.android.junit5) apply false
    alias(libs.plugins.gradle.versions) apply false
    alias(libs.plugins.version.catalog.update) apply false
}

apply plugin: libs.plugins.binary.compatibility.validator.get().pluginId
apply plugin: libs.plugins.nexus.staging.get().pluginId
apply plugin: libs.plugins.version.catalog.update.get().pluginId

apiValidation {
    ignoredProjects += ["sample"]
    ignoredPackages += [
        "com.chuckerteam.chucker.internal",
        "com.chuckerteam.chucker.databinding"
    ]
}

def isNonStable(String version) {
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { kw -> version.toUpperCase().contains(kw) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

versionCatalogUpdate {
    versionSelector {
        !(it.candidate.version.contains('SNAPSHOT') || it.candidate.version.contains('ALPHA'))
    }
}

allprojects {
    version = VERSION_NAME
    group = GROUP

    tasks.withType(Test) {
        testLogging {
            events "skipped", "failed", "passed"
        }
    }

    apply plugin: VersionsPlugin
    tasks.named("dependencyUpdates").configure {
        rejectVersionIf {
            isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)
        }
    }
}

task installGitHook(type: Copy) {
    from new File(rootProject.rootDir, 'pre-commit')
    into { new File(rootProject.rootDir, '.git/hooks') }
//    fileMode 0777
}

task clean(type: Delete) {
    dependsOn(installGitHook)
    delete rootProject.buildDir
}

ext {
    minSdkVersion = 24
    targetSdkVersion = 35
    compileSdkVersion = 35
}

nexusStaging {
    username = findProperty("NEXUS_USERNAME")
    password = findProperty("NEXUS_PASSWORD")
    stagingProfileId = "ea09119de9f4"
}
