import com.github.benmanes.gradle.versions.VersionsPlugin

plugins {
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.kapt) apply false
    alias(libs.plugins.ksp) apply false
//    alias(libs.plugins.apollo) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.binary.compatibility.validator) apply false
    alias(libs.plugins.wire) apply false
    alias(libs.plugins.nexus.staging) apply false
    alias(libs.plugins.android.junit5) apply false
    alias(libs.plugins.gradle.versions) apply false
    alias(libs.plugins.version.catalog.update) apply false
}

apply plugin: libs.plugins.binary.compatibility.validator.get().pluginId
apply plugin: libs.plugins.nexus.staging.get().pluginId
apply plugin: libs.plugins.version.catalog.update.get().pluginId

apiValidation {
    ignoredProjects += ["sample"]
    ignoredPackages += [
        "com.chuckerteam.chucker.internal",
        "com.chuckerteam.chucker.databinding"
    ]
}
def isNonStable(String version) {
    def stableKeywords = ['RELEASE', 'FINAL', 'GA', 'STABLE'].any { kw ->
        version.toUpperCase().contains(kw)
    }

    def unstableKeywords = ['SNAPSHOT', 'ALPHA', 'BETA', 'RC', 'CR', 'DEV', 'PREVIEW', 'MILESTONE'].any { kw ->
        version.toUpperCase().contains(kw)
    }

    def numericRegex = /^[0-9]+(\.[0-9]+)*(-[0-9]+)?$/

    def preReleaseRegex = /(?i).*-(alpha|a|beta|b|rc|cr|dev|preview|milestone|m)\d*$/

    return unstableKeywords ||
        (!stableKeywords && !(version ==~ numericRegex) && version ==~ preReleaseRegex)
}

versionCatalogUpdate {
    versionSelector {
        !isNonStable(it.candidate.version)
    }
    //   https://github.com/littlerobots/version-catalog-update-plugin
    pin {
        versions = ["androidGradle", "wire"]
    }
}

allprojects {
    version = VERSION_NAME
    group = GROUP

    tasks.withType(Test) {
        testLogging {
            events "skipped", "failed", "passed"
        }
    }

    apply plugin: VersionsPlugin

    tasks.named("dependencyUpdates").configure {
        rejectVersionIf {
            isNonStable(it.candidate.version)
        }

//        // Optional: Also reject versions with specific patterns globally
//        componentSelection { all ->
//            String candidate = it.candidate.version
//            if (isNonStable(candidate)) {
//                it.reject("Release candidate")
//            }
//        }
    }
}

task installGitHook(type: Copy) {
    from new File(rootProject.rootDir, 'pre-commit')
    into { new File(rootProject.rootDir, '.git/hooks') }
//    fileMode 0777
}

task clean(type: Delete) {
    dependsOn(installGitHook)
    delete rootProject.buildDir
}

ext {
    minSdkVersion = 24
    targetSdkVersion = 36
    compileSdkVersion = 36
}

nexusStaging {
    username = findProperty("NEXUS_USERNAME")
    password = findProperty("NEXUS_PASSWORD")
    stagingProfileId = "ea09119de9f4"
}
