apply plugin: libs.plugins.android.library.get().pluginId
apply plugin: libs.plugins.kotlin.android.get().pluginId

android {
    compileSdk rootProject.compileSdkVersion
    namespace "com.chuckerteam.chucker"

    compileOptions {
        kotlinOptions.freeCompilerArgs += [
            '-module-name', "com.github.ChuckerTeam.Chucker.library-no-op",
            "-Xexplicit-api=strict"
        ]
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlin {
        jvmToolchain(11)
    }

    buildFeatures {
        buildConfig = false
    }

    defaultConfig {
        minSdk rootProject.minSdkVersion
    }

    lintOptions {
        warningsAsErrors true
        abortOnError true
        disable 'RtlEnabled'
        disable 'GradleDependency'
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencies {
    api platform(libs.okhttp.bom)
    api libs.okhttp
    implementation libs.kotlin.stdlib
}

apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
apply from: rootProject.file('gradle/kotlin-static-analysis.gradle')
